//
//  JNSolution2.m
//  ProjectEulerSolutions
//
//  Created by Jonathan Nobels on 2017-02-08.
//  Copyright © 2017 JNobels. All rights reserved.
//

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#import "JNSolution2.h"

@implementation JNSolution2

static const long max = 4000000;

- (id)init
{
    self = [super init];
    self.title = @"2: Sum of even fibs below 4M";
    self.problemDescription = @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n"
                              @"1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...\n"
                              @"By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n\n";
    return self;
}

- (void)run
{
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [self output:self.problemDescription];
        long fib = 1;
        long lastFib = 1;
        long sum = 0;
        while(fib <= max) {
            long temp = fib;
            fib = fib + lastFib;
            lastFib = temp;
            if(fib%2 == 0) {
                sum += fib;
            }
        }
        [self output:[NSString stringWithFormat:@"Sum of even fibs less that %ld is %ld", max, sum] ];
    });

}

- (void)stop
{
    //Do nothing...
}

@end
